/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package front;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import ObjectosNegocio.Actividades;
import javax.swing.table.DefaultTableModel;
import DAO.PendientesDAO;
import java.util.List;

/**
 *
 * @author danie
 */
public class FramePrincipal extends javax.swing.JFrame {

    private final int TIEMPO_DESCANSO = 1;
    private final int TIEMPO_TRABAJO = 2;
    private final int TIEMPO_DESCANSO_LARGO = 3;
    PendientesDAO PendienteControl = new PendientesDAO();

    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        lblindicador.setVisible(false);
        btnContinuar.setVisible(false);
        t = new Timer(10, acciones);
        timerLB = new Timer(500, accionesLblParpadeante);
        this.cargarTabla();
        actualizarLabel();
        actualizaLblContadorDescansos();
    }

    private boolean esDescanso = false;
    private byte contDescansos = 0;
    private boolean parpadea = false;
    private boolean banderaPausa = true;
    private Timer t;
    private Timer timerLB;
    private int m, s, cs;
    private int contParpadeante;

    private ActionListener acciones = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent ae) {
            /*
            cs++;
            if (cs == 100) {
                cs = 0;
                ++s;
            }
            if (s == 60) {
                s = 0;
                ++m;
            }
            actualizarLabel();
            if (m == 5) {
                pararYAvisar();
            }
             */
            if (cs > 0) {
                cs--;
            } else {
                if (s > 0) {
                    s--;
                    cs = 99;
                } else if (m > 0) {
                    m--;
                    s = 59;
                    cs = 99;
                }
            }
            if (s <= 5) {
                mostrarIndicador();
            }
            actualizarLabel();
        }
    };

    private void setTiempos(int tipo) {
        switch (tipo) {
            case TIEMPO_DESCANSO:
                m = 0;
                s = 10;
                cs = 0;
                break;
            case TIEMPO_TRABAJO:
                m = 0;
                s = 20;
                cs = 0;
                break;
            case TIEMPO_DESCANSO_LARGO:
                m = 0;
                s = 15;
                cs = 0;
                break;
        }
    }

    private boolean banderaYaActivado;

    private void mostrarIndicador() {
        if (s == 0 && m == 0 && cs == 0) {
            lblindicador.setText("Se ha acabado el tiempo");
            btnContinuar.setVisible(true);
        } else {
            lblindicador.setVisible(true);
            lblindicador.setText("Faltan " + s + " segundos para acabar");
        }
    }

    private void actualizarLabel() {
        String tiempo = (m <= 9 ? "0" : "") + m + ":" + (s <= 9 ? "0" : "") + s + ":" + (cs <= 9 ? "0" : "") + cs;
        lblTiempo.setText(tiempo);
    }
    
    private ActionListener accionesLblParpadeante = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent ae) {
            if (contParpadeante % 2 == 0) {
                lblTiempo.setVisible(false);
            } else {
                lblTiempo.setVisible(true);
            }
            contParpadeante++;
        }
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTiempo = new javax.swing.JLabel();
        btnEmpezar = new javax.swing.JButton();
        btnPausar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPendientes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Btn_Agregar_Tarea = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla_Terminada = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        lblindicador = new javax.swing.JLabel();
        btnContinuar = new javax.swing.JButton();
        lblContadorDescansos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblTiempo.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblTiempo.setText("00:00:00");
        lblTiempo.setToolTipText("");

        btnEmpezar.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnEmpezar.setText("Empezar");
        btnEmpezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpezarActionPerformed(evt);
            }
        });

        btnPausar.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnPausar.setText("Pausar");
        btnPausar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPausarActionPerformed(evt);
            }
        });

        tblPendientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Actividad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPendientes);
        if (tblPendientes.getColumnModel().getColumnCount() > 0) {
            tblPendientes.getColumnModel().getColumn(0).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Tareas Terminada");

        Btn_Agregar_Tarea.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Btn_Agregar_Tarea.setText("Agregar Tarea");
        Btn_Agregar_Tarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Agregar_TareaActionPerformed(evt);
            }
        });

        Tabla_Terminada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Acitividad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Tabla_Terminada);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Tareas Pendientes");

        lblindicador.setForeground(new java.awt.Color(255, 51, 51));
        lblindicador.setText("INDICADOR");
        lblindicador.setToolTipText("");

        btnContinuar.setText("Continuar");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        lblContadorDescansos.setText("Contador de Descansos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(209, 209, 209)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(Btn_Agregar_Tarea, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(282, 282, 282)
                .addComponent(jLabel1)
                .addGap(99, 99, 99))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(310, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblindicador, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnContinuar))
                        .addGap(31, 31, 31))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblContadorDescansos, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(lblTiempo)
                .addGap(18, 18, 18)
                .addComponent(btnEmpezar)
                .addGap(18, 18, 18)
                .addComponent(btnPausar)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(lblindicador)
                                .addGap(18, 18, 18)
                                .addComponent(btnContinuar))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnEmpezar)
                                    .addComponent(btnPausar))))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblContadorDescansos)
                        .addGap(18, 18, 18)
                        .addComponent(Btn_Agregar_Tarea, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1))
                .addGap(141, 141, 141))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmpezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpezarActionPerformed
        if (esDescanso) {
            if (contDescansos == 5) {
                setTiempos(TIEMPO_DESCANSO_LARGO);
            } else {
                setTiempos(TIEMPO_DESCANSO);
            }
        } else {
            setTiempos(TIEMPO_TRABAJO);
        }
        t.start();
        btnEmpezar.setEnabled(false);
        btnPausar.setEnabled(true);
        btnContinuar.setVisible(false);
        lblindicador.setVisible(false);
    }//GEN-LAST:event_btnEmpezarActionPerformed

    private void btnPausarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPausarActionPerformed
        if (banderaPausa) {
            t.stop();
            timerLB.start();
            btnPausar.setText("Reanudar");
            banderaPausa = false;
        } else {
            timerLB.stop();
            lblTiempo.setVisible(true);
            t.restart();
            btnPausar.setText("Pausar");
            banderaPausa = true;
            timerLB.stop();
        }
    }//GEN-LAST:event_btnPausarActionPerformed

    public void cargarTabla() {
        this.PendienteControl.crearConexion();
        List<Actividades> list = this.PendienteControl.consultar();
        System.out.println(list);
        DefaultTableModel model = (DefaultTableModel) tblPendientes.getModel();
        model.setRowCount(0);
        list.forEach(pendiente -> {
            model.addRow(new Object[]{
                pendiente.getNombre_Tarea(),});
        });
    }


    private void Btn_Agregar_TareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Agregar_TareaActionPerformed
//        Frm_Agregar panel = new Frm_Agregar();
//        panel.setVisible(true);

        String actividad = JOptionPane.showInputDialog(rootPane, "Tarea", "Agregar", JOptionPane.QUESTION_MESSAGE);
        List<Actividades> list = this.PendienteControl.consultar();
        if (actividad.isEmpty() || actividad.isBlank()) {
            JOptionPane.showMessageDialog(rootPane, "La actividad esta vacia", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (actividad.length() > 100) {
            JOptionPane.showMessageDialog(rootPane, "Logitud mayor a 100", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Actividades New_actividad = new Actividades(actividad);
        if (list.contains(New_actividad)) {
            JOptionPane.showMessageDialog(rootPane, "La actividad ya existe", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        PendienteControl.agregar(New_actividad);
        JOptionPane.showMessageDialog(rootPane, "La actividad se agrego con exito!! ", "Listo", JOptionPane.INFORMATION_MESSAGE);
        this.cargarTabla();
    }//GEN-LAST:event_Btn_Agregar_TareaActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        if (!esDescanso) {
            if (contDescansos < 5) {
                contDescansos += 1;
            }
            banderaYaActivado = false;
        }
        actualizaLblContadorDescansos();
        if (contDescansos == 5) {
            contDescansos = 0;
        }
        esDescanso = !esDescanso;
        btnEmpezarActionPerformed(null);
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void actualizaLblContadorDescansos() {
        switch (contDescansos) {
            case 4 ->
                lblContadorDescansos.setText("El siguiente descanso sera largo");
            case 5 ->
                lblContadorDescansos.setText("Este es el descanso largo");
            default ->
                lblContadorDescansos.setText("Faltan " + (4 - contDescansos) + " descansos para el siguiente descanso largo");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Agregar_Tarea;
    private javax.swing.JTable Tabla_Terminada;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnEmpezar;
    private javax.swing.JButton btnPausar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblContadorDescansos;
    private javax.swing.JLabel lblTiempo;
    private javax.swing.JLabel lblindicador;
    private javax.swing.JTable tblPendientes;
    // End of variables declaration//GEN-END:variables
}
